version: '3.7'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    mem_limit: 500m
    cpus: 1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  redis:
    container_name: "redis"
    image: redis:6.2.5
    mem_limit: 500m
    cpus: 1
    ports:
      - 6379:6379